try {
  process.loadEnvFile(".env");
} catch {
  // Environment variables may already be supplied by the shell or CI.
}

import postgres from "postgres";

const databaseUrl = process.env.DATABASE_URL;
const email = process.env.ADMIN_EMAIL?.trim().toLowerCase();
const passwordHash = process.env.ADMIN_PASSWORD_HASH;

if (!databaseUrl || !email || !passwordHash) {
  console.error(
    "Set DATABASE_URL, ADMIN_EMAIL, and ADMIN_PASSWORD_HASH before running the admin seed.",
  );
  process.exit(1);
}

if (!email.includes("@") || email.length > 320) {
  console.error("ADMIN_EMAIL must be a valid email address.");
  process.exit(1);
}

if (!passwordHash.startsWith("pbkdf2_sha256$")) {
  console.error("ADMIN_PASSWORD_HASH must be generated by npm run admin:hash.");
  process.exit(1);
}

const sql = postgres(databaseUrl, { max: 1 });

try {
  await sql`
    INSERT INTO admin_users (email, password_hash, is_active)
    VALUES (${email}, ${passwordHash}, true)
    ON CONFLICT (email)
    DO UPDATE SET
      password_hash = EXCLUDED.password_hash,
      is_active = true,
      updated_at = now()
  `;

  console.log(`Admin account provisioned for ${email}.`);
} finally {
  await sql.end();
}
